# Generated by Django 6.1 on 2026-08-19 09:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(max_length=255, unique=True)),
                ('created_on', models.DateField(auto_now_add=True, verbose_name='Date Enregistrement')),
                ('nom_ese', models.CharField(max_length=255, unique=True, verbose_name='Nom Entreprise')),
                ('schema_sigle', models.CharField(max_length=255, unique=True, verbose_name='Sigle Entreprise')),
                ('nom_domaine', models.CharField(default='localhost', max_length=255, unique=True, verbose_name='Nom Domaine Entreprise')),
                ('description_ese', models.TextField(blank=True, default='Faire une description', null=True, verbose_name='Description Entreprise')),
                ('email', models.EmailField(max_length=255, unique=True, validators=[django.core.validators.EmailValidator(message='Email invalide')], verbose_name='Email Entreprise')),
                ('mobile', models.CharField(max_length=255, null=True, verbose_name='N° Telephone')),
            ],
        ),
        migrations.CreateModel(
            name='Validation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_ese', models.CharField(max_length=255, verbose_name='Nom Entreprise')),
                ('schema_name', models.CharField(max_length=255)),
            ],
        ),
    ]
