# Generated by Django 6.1 on 2026-08-19 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nparc', models.CharField(max_length=20)),
                ('noptim', models.CharField(max_length=20)),
                ('immat', models.CharField(max_length=20)),
                ('nature', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
                ('marque', models.CharField(max_length=20)),
                ('modele', models.CharField(max_length=20)),
                ('serie', models.CharField(max_length=20)),
                ('energie', models.CharField(max_length=20)),
                ('puissance', models.FloatField()),
                ('type_compt', models.CharField(choices=[('H', 'H'), ('KM', 'KM')], max_length=10)),
                ('annee_mes', models.DateField(max_length=20)),
                ('statut', models.DateField(max_length=20)),
                ('affectation', models.DateField(max_length=20)),
                ('site', models.DateField(max_length=20)),
                ('alert_compt', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
