# Generated by Django 6.1 on 2026-08-20 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ressources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=255)),
                ('prenom', models.CharField(blank=True, max_length=255)),
                ('fonction', models.CharField(blank=True, max_length=255)),
                ('site', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='vehicules',
            name='responsable_sabc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vehicules',
            name='alert_compt',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
