# Generated by Django 6.1 on 2026-08-24 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ressources', '0002_personnel_vehicules_responsable_sabc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicules',
            name='affectation',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicules',
            name='annee_mes',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicules',
            name='puissance',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='vehicules',
            name='site',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicules',
            name='statut',
            field=models.CharField(max_length=20),
        ),
    ]
