# Generated by Django 6.1 on 2026-08-24 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ressources', '0004_alter_vehicules_affectation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicules',
            name='affectation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
