# Generated by Django 6.1 on 2026-08-24 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ressources', '0005_alter_vehicules_affectation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicules',
            name='marque',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehicules',
            name='modele',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehicules',
            name='serie',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
