# Generated by Django 6.1 on 2026-08-19 09:23

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id_enreg', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('schema_name', models.CharField(max_length=255, unique=True)),
                ('created_on', models.DateField(auto_now_add=True, verbose_name='Date Enregistrement')),
                ('nom_ese', models.CharField(max_length=255, unique=True, verbose_name='Nom Entreprise')),
                ('schema_sigle', models.CharField(max_length=255, unique=True, verbose_name='Sigle Entreprise')),
                ('nom_domaine', models.CharField(default='localhost', max_length=255, unique=True, verbose_name='Nom Domaine Entreprise')),
                ('description_ese', models.TextField(blank=True, default='Faire une description', null=True, verbose_name='Description Entreprise')),
                ('email', models.EmailField(max_length=255, unique=True, validators=[django.core.validators.EmailValidator(message='Email invalide')], verbose_name='Email Entreprise')),
                ('mobile', models.CharField(max_length=255, null=True, verbose_name='N° Telephone')),
                ('ese_activate', models.BooleanField(default=False, verbose_name='Activation Entreprise')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='Client.clients')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
