# Generated by Django 6.1 on 2026-08-19 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Ressources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compt', models.PositiveIntegerField(blank=True, null=True)),
                ('date_compt', models.DateField(auto_now_add=True)),
                ('user_compt', models.CharField(max_length=25)),
                ('veh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compteur_veh', to='Ressources.vehicules')),
            ],
        ),
        migrations.CreateModel(
            name='PlanningEp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compt_ep', models.PositiveIntegerField(blank=True, null=True)),
                ('date_recept', models.DateField()),
                ('date_ent', models.DateField()),
                ('type_ep', models.CharField(max_length=15)),
                ('etat', models.CharField(choices=[('EFFECTUE', 'EFFECTUE'), ('NON EFFECTUE', 'NON EFFECTUE')], default='NON EFFECTUE', max_length=15)),
                ('statut', models.CharField(choices=[('PLANIFIE', 'PLANIFIE'), ('NON PLANIFIE', 'NON PLANIFIE')], default='PLANIFIE', max_length=15)),
                ('numbt', models.CharField(blank=True, max_length=20, null=True)),
                ('observation', models.CharField(blank=True, choices=[('', ''), ('ENGIN PAS LIBERE', 'ENGIN PAS LIBERE'), ('COMPTEUR NON ECHU', 'COMPTEUR NON ECHU'), ('ENGIN EN PANNE', 'ENGIN EN PANNE')], max_length=255, null=True)),
                ('veh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planning_veh', to='Ressources.vehicules')),
            ],
        ),
        migrations.CreateModel(
            name='SuiviEp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_ep', models.CharField(blank=True, max_length=10, null=True)),
                ('date_last_ep', models.DateField()),
                ('cpt_last_ep', models.PositiveIntegerField()),
                ('cpt_next_ep', models.PositiveIntegerField()),
                ('cpt_actuel', models.PositiveIntegerField()),
                ('ecart', models.FloatField()),
                ('statut', models.CharField(choices=[('R.A.S', 'R.A.S'), ('A vidanger', 'A vidanger'), ('En dépassement', 'En dépassement')], default='R.A.S', max_length=20)),
                ('program_ep', models.CharField(max_length=10)),
                ('bt', models.CharField(max_length=20)),
                ('veh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suivi_veh', to='Ressources.vehicules')),
            ],
        ),
    ]
