# Generated by Django 6.1 on 2026-08-20 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Preventive', '0001_initial'),
        ('Ressources', '0002_personnel_vehicules_responsable_sabc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suiviep',
            name='responsable',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='compteur',
            name='user_compt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compteur_personne', to='Ressources.personnel'),
        ),
        migrations.AlterField(
            model_name='suiviep',
            name='date_last_ep',
            field=models.DateField(blank=True, null=True),
        ),
    ]
