# Generated by Django 6.1 on 2026-08-24 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Preventive', '0002_suiviep_responsable_alter_compteur_user_compt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suiviep',
            name='bt',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
