# Generated by Django 6.1 on 2026-08-24 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Preventive', '0003_alter_suiviep_bt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suiviep',
            name='date_last_ep',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
