# Generated by Django 6.1 on 2026-08-24 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Preventive', '0004_alter_suiviep_date_last_ep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suiviep',
            name='statut',
            field=models.CharField(choices=[('R.A.S', 'R.A.S'), ('A VIDANGER', 'A VIDANGER'), ('EN DEPASSEMENT', 'EN DEPASSEMENT')], default='R.A.S', max_length=20),
        ),
    ]
