# Generated by Django 6.1 on 2026-08-25 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Preventive', '0005_alter_suiviep_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suiviep',
            name='statut',
            field=models.CharField(choices=[('RAS', 'RAS'), ('A VIDANGER', 'A VIDANGER'), ('EN DEPASSEMENT', 'EN DEPASSEMENT')], default='R.A.S', max_length=20),
        ),
    ]
