# Generated by Django 6.1 on 2026-08-25 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Preventive', '0006_alter_suiviep_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suiviep',
            name='program_ep',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='suiviep',
            name='statut',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
