# Generated by Django 6.1 on 2026-08-31 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Preventive', '0007_alter_suiviep_program_ep_alter_suiviep_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suiviep',
            name='statut',
            field=models.CharField(blank=True, choices=[('RAS', 'RAS'), ('A VIDANGER', 'A VIDANGER'), ('EN DEPASSEMENT', 'EN DEPASSEMENT')], max_length=30, null=True),
        ),
    ]
