# Generated by Django 6.1 on 2026-08-31 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Preventive', '0009_alter_suiviep_last_ep_alter_suiviep_program_ep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suiviep',
            name='date_last_ep',
            field=models.DateField(blank=True, max_length=30, null=True),
        ),
    ]
